# Generated by Django 6.0.6 on 2026-06-15 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('score_percent', models.FloatField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Тестовая сессия',
                'verbose_name_plural': 'Тестовые сессии',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.question')),
                ('selected_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.answer')),
            ],
            options={
                'verbose_name': 'Запись ответа',
                'verbose_name_plural': 'Записи ответов',
            },
        ),
    ]
