# Generated by Django 6.0.6 on 2026-07-09 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_question_points_question_question_type_and_more'),
        ('tests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrecord',
            name='matching_pairs',
            field=models.JSONField(blank=True, default=dict, verbose_name='Пары соответствия'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='points_earned',
            field=models.FloatField(default=0, verbose_name='Получено баллов'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='points_max',
            field=models.FloatField(default=0, verbose_name='Макс. баллов'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='selected_answers',
            field=models.JSONField(blank=True, default=list, verbose_name='Выбранные ответы (ID)'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='earned_points',
            field=models.FloatField(default=0, verbose_name='Набрано баллов'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='ent_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные ЕНТ (секции, предметы)'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='is_ent',
            field=models.BooleanField(default=False, verbose_name='ЕНТ тест'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='time_limit',
            field=models.IntegerField(default=14400, verbose_name='Лимит времени (сек)'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='total_points',
            field=models.FloatField(default=0, verbose_name='Всего баллов'),
        ),
        migrations.AlterField(
            model_name='answerrecord',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.answer'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='subjects.subject'),
        ),
        migrations.CreateModel(
            name='TestSectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('history', 'История Казахстана'), ('reading', 'Грамотность чтения'), ('math_lit', 'Математическая грамотность'), ('profile1', 'Профильный предмет 1'), ('profile2', 'Профильный предмет 2')], max_length=12)),
                ('total_questions', models.IntegerField(default=0)),
                ('answered', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('points_earned', models.FloatField(default=0)),
                ('points_max', models.FloatField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_results', to='tests.testsession')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Результат секции',
                'verbose_name_plural': 'Результаты секций',
                'unique_together': {('session', 'section')},
            },
        ),
    ]
