# Generated by Django 6.0.6 on 2026-07-16 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_answerrecord_matching_pairs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
