# Generated by Django 6.0.6 on 2026-09-02 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        ('tests', '0006_testsessionquestion_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='duel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='gamification.duel', verbose_name='Дуэль'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='mode',
            field=models.CharField(choices=[('standard', 'Обычный тест'), ('rush', 'Question Rush'), ('duel', 'Дуэль')], default='standard', max_length=10, verbose_name='Режим теста'),
        ),
    ]
