# Generated by Django 6.0.6 on 2026-06-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_answer_image_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ai_explanation',
            field=models.TextField(blank=True, default='', verbose_name='AI-объяснение'),
        ),
        migrations.AddField(
            model_name='question',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(default='ru', max_length=5, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='question',
            name='source_type',
            field=models.CharField(choices=[('collected', 'Собранный'), ('authorial', 'Авторский')], db_index=True, default='collected', max_length=12, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='question',
            name='verification_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('verified', 'Проверен'), ('rejected', 'Отклонён')], db_index=True, default='draft', max_length=12, verbose_name='Статус проверки'),
        ),
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False), models.Q(('external_id', ''), _negated=True)), fields=('source_type', 'external_id'), name='uniq_external_id_per_source'),
        ),
    ]
