# Generated by Django 6.0.6 on 2026-07-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_question_ai_explanation_question_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Drive file ID'),
        ),
    ]
