# Generated by Django 6.0.6 on 2026-07-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_question_image_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.FloatField(default=1, verbose_name='Баллы'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Один правильный'), ('multiple_choice', 'Несколько правильных'), ('matching', 'На соответствие')], default='single_choice', max_length=20, verbose_name='Тип вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, choices=[('history', 'История Казахстана'), ('reading', 'Грамотность чтения'), ('math_lit', 'Математическая грамотность'), ('profile1', 'Профильный предмет 1'), ('profile2', 'Профильный предмет 2')], default='', max_length=12, verbose_name='Секция ЕНТ'),
        ),
    ]
