# Generated by Django 6.0.6 on 2026-07-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_question_points_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AddField(
            model_name='subject',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Виден ученикам'),
        ),
        migrations.AddField(
            model_name='subject',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('mandatory', 'Обязательный (ЕНТ)'), ('profile', 'Профильный (ЕНТ)'), ('other', 'Дополнительный')], default='profile', max_length=12, verbose_name='Тип предмета'),
        ),
    ]
