# Generated by Django 6.0.6 on 2026-07-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_alter_subject_options_subject_is_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='question_count',
            field=models.IntegerField(default=10, verbose_name='Кол-во вопросов'),
        ),
        migrations.AddField(
            model_name='subject',
            name='time_limit',
            field=models.IntegerField(default=600, verbose_name='Лимит времени (сек)'),
        ),
    ]
