# Generated by Django 6.0.6 on 2026-07-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_subject_question_count_subject_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='show_in_profiles',
            field=models.BooleanField(default=True, verbose_name='Показывать в выборе профилей'),
        ),
    ]
