# Generated by Django 6.0.6 on 2026-07-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_variant_topic_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='ent_max_score',
            field=models.FloatField(default=50, verbose_name='Макс. баллов на ЕНТ'),
        ),
        migrations.AddField(
            model_name='subject',
            name='ent_question_count',
            field=models.IntegerField(default=40, verbose_name='Вопросов на ЕНТ'),
        ),
        migrations.AddField(
            model_name='subject',
            name='ent_threshold',
            field=models.FloatField(default=5, verbose_name='Пороговый балл ЕНТ'),
        ),
    ]
