# Generated by Django 6.0.6 on 2026-07-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('uni_type', models.CharField(choices=[('national', 'Национальный'), ('medical', 'Медицинский'), ('pedagogical', 'Педагогический'), ('technical', 'Технический'), ('it', 'IT'), ('agro', 'Аграрный'), ('other', 'Другой')], max_length=20, verbose_name='Тип')),
                ('icon', models.CharField(default='🏛️', max_length=10, verbose_name='Иконка')),
                ('min_score', models.IntegerField(verbose_name='Проходной балл')),
                ('specializations', models.CharField(max_length=500, verbose_name='Специальности')),
                ('info', models.TextField(blank=True, verbose_name='Доп. информация')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Вуз',
                'verbose_name_plural': 'Вузы',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
