# Generated by Django 6.0.6 on 2026-09-02 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0011_subject_ent_max_score_subject_ent_question_count_and_more'),
        ('tests', '0006_testsessionquestion_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ids', models.JSONField(default=list, verbose_name='ID вопросов дуэли')),
                ('num_questions', models.PositiveIntegerField(default=10, verbose_name='Кол-во вопросов')),
                ('status', models.CharField(choices=[('pending', 'Ожидает соперника'), ('active', 'В процессе'), ('completed', 'Завершена'), ('declined', 'Отклонена'), ('expired', 'Истекла')], default='pending', max_length=12, verbose_name='Статус')),
                ('is_draw', models.BooleanField(default=False, verbose_name='Ничья')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_challenged', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('challenger_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duel_as_challenger', to='tests.testsession')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duels_received', to=settings.AUTH_USER_MODEL, verbose_name='Соперник')),
                ('opponent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duel_as_opponent', to='tests.testsession')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duels', to='subjects.subject', verbose_name='Предмет')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duels_won', to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Дуэль',
                'verbose_name_plural': 'Дуэли',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, verbose_name='Код достижения')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата разблокировки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'constraints': [models.UniqueConstraint(fields=('user', 'code'), name='unique_user_achievement')],
            },
        ),
    ]
