# Generated by Django 6.0.6 on 2026-07-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_subject_show_in_profiles'),
        ('users', '0002_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_subjects',
            field=models.ManyToManyField(blank=True, to='subjects.subject', verbose_name='Предметы на дашборде'),
        ),
    ]
