# Generated by Django 6.0.6 on 2026-07-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_subject_show_in_profiles'),
        ('users', '0003_user_dashboard_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='subjects.subject', verbose_name='Профильные предметы ученика'),
        ),
    ]
